#5.	Revenue generated by each restaurant location in the last year, including location name and total revenue.
SELECT 
    RL.LocationName AS RestaurantLocation,
    SUM(ST.TotalRevenue) AS TotalRevenueGenerated
    
FROM SalesTransaction_tbl ST

INNER JOIN Order_tbl O
ON ST.SalesID = O.OrderID

INNER JOIN Reservation_tbl R
ON O.ReservationID = R.ReservationID

INNER JOIN RestaurantLocation_tbl RL
ON R.RestaurantLocationID = RL.LocationID

WHERE ST.SaleDate BETWEEN DATE_SUB(CURDATE(), INTERVAL 1 YEAR) AND CURDATE()

GROUP BY RL.LocationName

ORDER BY TotalRevenueGenerated DESC;
